### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by pulver22** [ar-tools/ar_tools#25]
Trying to compile this package I get the following error:

`Built target opencv_apps
svn: E000110: Unable to connect to a repository at URL 'svn://svn.code.sf.net/p/artoolkit/code/trunk/artoolkit'
svn: E000110: Can't connect to host 'svn.code.sf.net': Connection timed out
make[2]: *** [ar_tools/artoolkit/ARToolkit-prefix/src/ARToolkit-stamp/ARToolkit-download] Interrupt
make[1]: *** [ar_tools/artoolkit/CMakeFiles/ARToolkit.dir/all] Interrupt
make: *** [all] Interrupt
`

Is there a way to solve it and be able to compile the entire pkg? Also trying the demo launch files I got an error saying 

`ERROR: cannot launch node of type [ar_pose/ar_single]: can't locate node [ar_single] in package [ar_pose]
`

**Comment by dlaz** [comment]
I've answered this in the comment you made on another issue, but in general, for troubleshooting, please use http://answers.ros.org/questions/.
