### ISSUE TITLE
update stack.xml

### ISSUE THREAD

**Issue by procopiostein** [ar-tools/ar_tools#6]
Hi, I have contributed to this stack in the past but spent a long time without touching it. Now that I needed it back I saw that it has moved from ccny repo. 
I already created a wiki page for ar_tools at ros wiki, but stack.xml needs to be updated to reflect the new name and maintaners...
cheers

**Comment by LucidOne** [comment]
I think this is fixed, otherwise send me you contact information.

**Comment by procopiostein** [comment]
sure! i'm also willing to be one of the maintainers, if that is ok for you.

**Comment by LucidOne** [comment]
Can you make a pull request to add yourself to the list of maintainers?
